name: Build, Push and Deploy Docker Images on Self-Hosted Runner

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: [self-hosted, linux]  
    steps:
      # 1. Клонирование репозиториев и сборка образов

      - name: Checkout frontend repository
        uses: actions/checkout@v3
        with:
          repository: BattleshipGameCSIT/frontend 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image for Frontend
        run: |
          docker build -t battleship-frontend:latest .
          docker push battleship-frontend:latest

      - name: Checkout backend repository 
        uses: actions/checkout@v3
        with:
          repository: BattleshipGameCSIT/backend
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image for Backend
        run: |
          docker build -t battleship-backend:latest .
          docker push battleship-backend:latest

      - name: Checkout gameserver repository 
        uses: actions/checkout@v3
        with:
          repository: BattleshipGameCSIT/gameserver
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image for Gameserver
        run: |
          docker build -t battleship-gameserver:latest .
          docker push battleship-gameserver:latest

      # 2. Логинимся в Docker Registry (если нужно)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Запуск Docker Compose на self-hosted сервере
      - name: Deploy to Self-Hosted Server with Docker Compose
        run: |
          # Переходим в директорию с docker-compose файлами
          cd /path/to/docker-compose

          # Загрузим последние образы
          docker pull user/repo1-image:latest
          docker pull user/repo2-image:latest
          docker pull user/repo3-image:latest

          # Останавливаем контейнеры, если они уже запущены, и запускаем новые
          docker-compose down || true
          docker-compose up -d